#Chile - Universidad Adolfo Ibáñez (UAI)
##Curso Analítica Textual
### Prediction-based Word Embeddings (Inglés)

# Spanish Pipeline (Small)

In [1]:
#Importar Librerías
import spacy
import numpy as np

In [2]:
#Cargar Data
data = [
        "Mi mamá ama las manzanas", 
        "Katy Perry odia las manzanas.",
        "Orlando Bloom compró acciones en NotCo",
        "Mi hermana nació en Melipilla",
        "Katy Perry visitó Melipilla",
        "Los fundadores de NotCo nacieron en Melipilla",
        "No me gustó la comida en Melipilla",
        "Orlando Bloom compró una casa en Melipilla",
        "Mi postulación a NotCo fue rechazada",
        "Mi papá fue al colegio en Melipilla",
        "El que fue a Melipilla perdió su silla",
        "No me gustan los productos de NotCo",
        "Anoche hubieron protestas contra NotCo"
        ]

In [3]:
#Descargar Pipeline (Spanish)
!python -m spacy download es_core_news_sm -q

✔ Download and installation successful
You can now load the package via spacy.load('es_core_news_sm')


In [4]:
#Cargar Pipeline
nlp_sm = spacy.load("es_core_news_sm")

In [6]:
#Crear Doc Object
doc_sm = nlp_sm(data[0])

In [7]:
#Validar Existencia Word Embeddings (GloVe)
for token in doc_sm:
  print(token.text,"---", token.has_vector)

Mi --- True
mamá --- True
ama --- True
las --- True
manzanas --- True


In [8]:
#Revisar Representación Vectorial (Token)
print("Dimensionalidad Word Embeddings:", doc_sm[0].vector.shape)
doc_sm[0].vector

Dimensionalidad Word Embeddings: (96,)


array([-0.08291206,  1.5179516 ,  2.0866835 , -0.7775131 , -1.9323261 ,
       -1.3215841 ,  1.4307604 ,  1.4977334 , -1.865532  ,  2.5524156 ,
        0.19386086, -0.6976349 ,  1.3644652 ,  1.307573  , -1.7472637 ,
        1.9935358 ,  0.89173627,  0.74685574, -0.269341  , -3.6297617 ,
        1.3759098 ,  1.5163943 ,  0.4289627 , -2.4989738 , -0.13432686,
       -3.2781174 , -1.5732719 ,  0.08936225,  3.2447412 ,  1.974828  ,
       -0.06628937,  3.3024466 , -0.99762905,  0.1857233 , -0.26706678,
       -0.83354765,  0.9691308 , -3.7616842 ,  0.3447376 ,  0.6280387 ,
        1.8265839 , -0.9263427 , -2.7162883 , -0.36014396, -1.3036525 ,
       -0.9307498 , -1.9783629 ,  2.3778107 ,  0.52810496,  1.0444435 ,
        2.8703322 ,  3.8083057 ,  1.4851146 , -0.1349554 , -2.3929126 ,
        0.39747813,  0.02701145,  0.88312984, -0.15027973, -2.153625  ,
       -1.8552997 ,  2.1231995 , -1.976579  ,  3.2550716 , -2.6254013 ,
       -0.40515196, -0.50842977, -1.791587  , -2.1946747 , -1.81

In [9]:
#Revisar Representación Vectorial (Documento - Promedio Simple)
print("Dimensionalidad Word Embeddings:", doc_sm.vector.shape)
doc_sm.vector

Dimensionalidad Word Embeddings: (96,)


array([ 0.760939  ,  0.85541743,  0.4260292 ,  0.55647624, -0.6168562 ,
       -1.3378676 ,  0.12358955,  1.3487178 , -0.9810215 ,  0.8468194 ,
        0.7199353 , -0.03840468,  0.52188003,  0.447141  , -1.843049  ,
        0.9985124 ,  0.68699837, -0.93423164, -1.0484489 , -1.5984409 ,
       -0.29564553,  1.7870337 ,  0.56477416, -0.8688095 , -0.03249631,
       -0.70188606,  0.6429666 ,  0.23658189,  0.71079874,  1.3037827 ,
        1.5162247 , -0.6439638 , -1.1343148 , -0.5854452 , -0.85461587,
        0.6526984 , -0.49109626, -2.300539  ,  0.0890262 , -0.16312584,
        0.0328876 , -0.27493104, -0.5258345 ,  1.7573414 ,  0.68465316,
        0.12872049, -0.3102977 ,  0.5451294 ,  0.09812834, -0.55265915,
       -0.05023498, -0.10670877,  0.9559191 , -0.4548791 , -2.0572727 ,
        0.64383876,  1.4566361 , -0.20564255, -1.2150301 , -1.0909631 ,
        0.3638121 ,  0.72967416, -1.6736    ,  0.50651103, -1.5428026 ,
        0.85319185,  0.19274811, -0.8288978 ,  0.19989768, -0.92

In [10]:
#Crear Representación Vectorial para Set Documentos
X_sm = list() #Para cada documento sacar representacion vectorial y guardarlo en una lista
for text in data:
  doc = nlp_sm(text)
  X_sm.append(doc.vector)

In [13]:
#Convertir Lista en Numpy Array. Mas facil procesar arreglos en numpy
X_sm_embeddings = np.array(X_sm)
print("Dimensionalidad Embeddings:", X_sm_embeddings.shape)

Dimensionalidad Embeddings: (13, 96)


# Spanish Pipeline (Medium)

In [14]:
#Descargar Pipeline (English)
!python -m spacy download es_core_news_md -q

✔ Download and installation successful
You can now load the package via spacy.load('es_core_news_md')


In [15]:
#Cargar Pipeline
nlp_md = spacy.load("es_core_news_md")

In [16]:
#Crear Doc Object
doc_md = nlp_md(data[0])

In [17]:
#Revisar Representación Vectorial (Token)
print("Dimensionalidad Word Embeddings:", doc_md[0].vector.shape)
doc_md[0].vector

Dimensionalidad Word Embeddings: (300,)


array([-1.9404e+00,  1.9105e+00, -9.3088e+00,  1.3549e+00,  4.1000e+00,
       -1.9104e-01, -2.2157e+00,  2.5863e-01,  2.1628e+00, -9.4065e+00,
        4.1135e+00, -3.8849e+00, -2.7939e+00, -3.0468e+00, -1.7454e+00,
        5.5956e-02,  9.9157e+00, -5.5204e+00,  3.4488e+00, -1.0240e+00,
       -8.0252e+00, -4.6070e+00,  5.2104e+00,  3.6452e+00, -3.2765e+00,
        1.2593e+00, -1.0383e+00, -1.2450e+00, -3.0145e+00,  1.2102e+01,
       -2.2211e+00,  6.2293e+00,  7.1747e+00, -5.9971e-01,  9.8436e+00,
        1.5869e+00,  1.5318e-01,  6.5774e+00, -9.9527e-01, -5.6178e+00,
        2.1957e+00, -1.7272e+00, -1.6804e+00, -5.4881e-01,  1.3629e+01,
       -6.9420e-01, -6.5158e-01,  1.4769e+01, -4.6708e+00, -2.1389e+00,
        2.8142e+00,  4.1257e+00, -5.6887e-03,  1.9842e+00,  3.5662e+00,
        2.6484e+00,  1.9626e+00, -8.1521e+00, -2.6347e+00, -5.0689e+00,
        7.0462e+00, -4.1781e+00,  1.0387e+00,  6.2273e+00,  1.7876e+00,
       -7.1278e+00, -2.3332e+00, -1.9547e+00,  3.8839e+00,  5.79

In [18]:
#Revisar Representación Vectorial (Documento - Promedio Simple)
print("Dimensionalidad Word Embeddings:", doc_md.vector.shape)
doc_md.vector

Dimensionalidad Word Embeddings: (300,)


array([-3.73145789e-02,  1.11617398e+00, -2.27069974e+00,  1.27130806e+00,
        4.44750023e+00, -1.44018805e+00, -1.46512508e+00,  9.62662041e-01,
       -3.74112219e-01,  3.24720234e-01, -7.45649934e-01, -1.62231612e+00,
       -1.31675136e+00, -8.57125938e-01, -2.11243200e+00, -1.65153289e+00,
        1.12183797e+00, -1.47405791e+00,  1.16760409e+00, -1.01790786e+00,
       -1.64601588e+00, -8.95667911e-01,  2.08914208e+00,  1.60221887e+00,
       -1.14509010e+00, -1.04997802e+00, -1.79203391e+00, -7.34925926e-01,
        6.44540012e-01,  4.02600193e+00,  1.45374203e+00,  4.91696030e-01,
        1.94976211e+00, -1.57360804e+00,  1.83575594e+00,  5.81106782e-01,
       -9.70035553e-01,  7.88300037e-01, -1.69487998e-01,  1.10347998e+00,
       -1.39476225e-01, -1.27673411e+00, -2.50613987e-01, -5.94108582e-01,
        3.23211408e+00, -4.72797692e-01, -1.41617990e+00,  2.93653989e+00,
       -8.36840272e-01, -4.92612600e-01, -1.17944017e-01,  4.27856028e-01,
       -1.26845747e-01,  